/**
 * Session Service - 处理会话和用户设置相关的业务逻辑
 */

import { BaseService, ServiceError } from "./base.service";

export interface UserSettings {
	theme: "light" | "dark" | "auto";
	fontSize: "tiny" | "small" | "medium" | "large";
	language: string;
	timezone: string;
	showThinking: boolean;
	autoCollapseMessages: boolean;
	enterToSend: boolean;
	markdownPreview: boolean;
	syntaxHighlighting: boolean;
	recentWorkspaces: Array<{
		path: string;
		name: string;
		lastAccessed: string;
	}>;
	keyboardShortcuts: Record<string, string>;
}

export interface WorkspaceInfo {
	path: string;
	name: string;
	isCurrent: boolean;
	sessionCount: number;
	lastAccessed: string;
	diskUsage?: {
		total: number;
		used: number;
		free: number;
	};
}

export interface SessionStats {
	totalSessions: number;
	totalMessages: number;
	totalTokens: number;
	activeSessions: number;
	favoriteSessions: number;
	recentActivity: Array<{
		sessionId: string;
		timestamp: string;
		action: string;
	}>;
}

export interface BackupInfo {
	id: string;
	timestamp: string;
	size: number;
	sessionCount: number;
	description?: string;
	autoGenerated: boolean;
}

export class SessionService extends BaseService {
	constructor() {
		super("SessionService", "/api");
	}

	/**
	 * 获取用户设置
	 */
	async getUserSettings(): Promise<UserSettings> {
		try {
			return await this.get<UserSettings>("/settings");
		} catch (error) {
			throw new ServiceError("GET_SETTINGS_FAILED", "Failed to get user settings", error);
		}
	}

	/**
	 * 更新用户设置
	 */
	async updateUserSettings(settings: Partial<UserSettings>): Promise<UserSettings> {
		try {
			return await this.post<UserSettings>("/settings/update", settings);
		} catch (error) {
			throw new ServiceError("UPDATE_SETTINGS_FAILED", "Failed to update user settings", error);
		}
	}

	/**
	 * 重置用户设置
	 */
	async resetUserSettings(): Promise<UserSettings> {
		try {
			return await this.post<UserSettings>("/settings/reset", {});
		} catch (error) {
			throw new ServiceError("RESET_SETTINGS_FAILED", "Failed to reset user settings", error);
		}
	}

	/**
	 * 获取当前工作空间
	 */
	async getCurrentWorkspace(): Promise<WorkspaceInfo> {
		try {
			return await this.get<WorkspaceInfo>("/workspace/current");
		} catch (error) {
			throw new ServiceError("GET_WORKSPACE_FAILED", "Failed to get current workspace", error);
		}
	}

	/**
	 * 切换工作空间
	 */
	async switchWorkspace(path: string): Promise<WorkspaceInfo> {
		try {
			return await this.post<WorkspaceInfo>("/workspace/switch", { path });
		} catch (error) {
			throw new ServiceError("SWITCH_WORKSPACE_FAILED", "Failed to switch workspace", error);
		}
	}

	/**
	 * 获取最近的工作空间列表
	 */
	async getRecentWorkspaces(limit: number = 10): Promise<WorkspaceInfo[]> {
		try {
			const response = await this.get<{ workspaces: WorkspaceInfo[] }>("/workspace/recent", { limit });
			return response.workspaces;
		} catch (error) {
			throw new ServiceError("GET_RECENT_WORKSPACES_FAILED", "Failed to get recent workspaces", error);
		}
	}

	/**
	 * 添加工件空间到最近列表
	 */
	async addToRecentWorkspaces(path: string): Promise<void> {
		try {
			await this.post("/workspace/add-recent", { path });
		} catch (error) {
			throw new ServiceError("ADD_RECENT_WORKSPACE_FAILED", "Failed to add workspace to recent", error);
		}
	}

	/**
	 * 从最近列表移除工作空间
	 */
	async removeFromRecentWorkspaces(path: string): Promise<void> {
		try {
			await this.post("/workspace/remove-recent", { path });
		} catch (error) {
			throw new ServiceError("REMOVE_RECENT_WORKSPACE_FAILED", "Failed to remove workspace from recent", error);
		}
	}

	/**
	 * 获取会话统计信息
	 */
	async getSessionStats(): Promise<SessionStats> {
		try {
			return await this.get<SessionStats>("/session/stats");
		} catch (error) {
			throw new ServiceError("GET_SESSION_STATS_FAILED", "Failed to get session stats", error);
		}
	}

	/**
	 * 导出会话数据
	 */
	async exportSessions(sessionIds: string[], format: "json" | "markdown" | "html" = "json"): Promise<Blob> {
		try {
			const response = await fetch(`/api/session/export?format=${format}`, {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify({ sessionIds }),
			});

			if (!response.ok) {
				throw new Error(`Export failed: ${response.statusText}`);
			}

			return await response.blob();
		} catch (error) {
			throw new ServiceError("EXPORT_SESSIONS_FAILED", "Failed to export sessions", error);
		}
	}

	/**
	 * 导入会话数据
	 */
	async importSessions(file: File): Promise<{ imported: number; failed: number }> {
		try {
			const formData = new FormData();
			formData.append("file", file);

			const response = await this.post<{ imported: number; failed: number }>("/session/import", formData);
			return response;
		} catch (error) {
			throw new ServiceError("IMPORT_SESSIONS_FAILED", "Failed to import sessions", error);
		}
	}

	/**
	 * 创建备份
	 */
	async createBackup(description?: string): Promise<BackupInfo> {
		try {
			return await this.post<BackupInfo>("/backup/create", { description });
		} catch (error) {
			throw new ServiceError("CREATE_BACKUP_FAILED", "Failed to create backup", error);
		}
	}

	/**
	 * 获取备份列表
	 */
	async getBackups(): Promise<BackupInfo[]> {
		try {
			const response = await this.get<{ backups: BackupInfo[] }>("/backup/list");
			return response.backups;
		} catch (error) {
			throw new ServiceError("GET_BACKUPS_FAILED", "Failed to get backups", error);
		}
	}

	/**
	 * 恢复备份
	 */
	async restoreBackup(backupId: string): Promise<void> {
		try {
			await this.post("/backup/restore", { backupId });
		} catch (error) {
			throw new ServiceError("RESTORE_BACKUP_FAILED", "Failed to restore backup", error);
		}
	}

	/**
	 * 删除备份
	 */
	async deleteBackup(backupId: string): Promise<void> {
		try {
			await this.post("/backup/delete", { backupId });
		} catch (error) {
			throw new ServiceError("DELETE_BACKUP_FAILED", "Failed to delete backup", error);
		}
	}

	/**
	 * 获取系统信息
	 */
	async getSystemInfo(): Promise<{
		platform: string;
		arch: string;
		nodeVersion: string;
		memory: {
			total: number;
			free: number;
			used: number;
		};
		disk: Array<{
			path: string;
			total: number;
			free: number;
			used: number;
		}>;
		cpu: {
			cores: number;
			model: string;
			speed: number;
		};
		uptime: number;
	}> {
		try {
			return await this.get("/system/info");
		} catch (error) {
			throw new ServiceError("GET_SYSTEM_INFO_FAILED", "Failed to get system info", error);
		}
	}

	/**
	 * 获取性能指标
	 */
	async getPerformanceMetrics(): Promise<{
		timestamp: string;
		memoryUsage: {
			rss: number;
			heapTotal: number;
			heapUsed: number;
			external: number;
		};
		cpuUsage: {
			user: number;
			system: number;
		};
		apiMetrics: {
			requestCount: number;
			errorCount: number;
			averageResponseTime: number;
			activeConnections: number;
		};
	}> {
		try {
			return await this.get("/system/metrics");
		} catch (error) {
			throw new ServiceError("GET_METRICS_FAILED", "Failed to get performance metrics", error);
		}
	}

	/**
	 * 清理临时文件
	 */
	async cleanupTempFiles(): Promise<{
		deleted: number;
		freed: number;
		errors: number;
	}> {
		try {
			return await this.post("/system/cleanup", {});
		} catch (error) {
			throw new ServiceError("CLEANUP_FAILED", "Failed to cleanup temp files", error);
		}
	}

	/**
	 * 重置应用状态
	 */
	async resetAppState(): Promise<void> {
		try {
			await this.post("/system/reset", {});
		} catch (error) {
			throw new ServiceError("RESET_APP_FAILED", "Failed to reset app state", error);
		}
	}
}

// 导出单例
export const sessionService = new SessionService();
